config/routes.rb
Roomidex::Application.routes.draw do
  
  resources :messages 

  resources :roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/accept' => 'roomidex_requests#accept', :as => :accept_roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/ignore' => 'roomidex_requests#ignore', :as => :ignore_roomidex_requests

  resources :roomidex_relationships

  root :to => "splash_page#index"

  resources :users

  # Auth resources
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/roomidex_relationship.rb
class RoomidexRelationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  validates_uniqueness_of :user_id, :scope => :friend_id

  def self.get_edge(first_id, second_id)
  	edge = self.get_directed_edge(first_id, second_id)
  	
  	if edge.size == 0 
  		edge = self.get_directed_edge(second_id, first_id)
  	end

  	edge
  end

  def self.get_directed_edge(first_id, second_id)
  	edge = RoomidexRelationship.where(
  		user_id: first_id,
  		receiver_id: second_id
	  )
  end
end

app/controllers/roomidex_relationships_controller.rb
class RoomidexRelationshipsController < ApplicationController
  before_action :set_roomidex_relationship, only: [:show, :edit, :update, :destroy]
  before_action :set_roomidex_relationships, only: [:index]

  # This class was created with scaffold, currently only need create and destroy,
  # so commenting out all else. 

  # # GET /roomidex_relationships
  # # GET /roomidex_relationships.json
  def index
  end

  # GET /roomidex_relationships/1
  # GET /roomidex_relationships/1.json
  def show
  end

  # # GET /roomidex_relationships/new
  # def new
  #   @roomidex_relationship = RoomidexRelationship.new
  # end

  # # GET /roomidex_relationships/1/edit
  # def edit
  # end

  # POST /roomidex_relationships
  # POST /roomidex_relationships.json
  def create
    @roomidex_relationship = current_user.roomidex_relationships.build(
      :friend_id => params[:friend_id]
    )

    respond_to do |format|
      if @roomidex_relationship.save
        format.html { 
          redirect_to @roomidex_relationship, 
          notice: 'Roomidex relationship was successfully created.' 
        }
        format.json { 
          render action: 'show', 
          status: :created, 
          location: @roomidex_relationship 
        }
      else
        format.html { 
          flash[:error] = "Unable to create Roomidex connection." 
          redirect_to :back
        }
        format.json { 
          render json: @roomidex_relationship.errors, 
          status: :unprocessable_entity 
        }
      end
    end
  end

  # PATCH/PUT /roomidex_relationships/1
  # # PATCH/PUT /roomidex_relationships/1.json
  # def update
  #   respond_to do |format|
  #     if @roomidex_relationship.update(roomidex_relationship_params)
  #       format.html { redirect_to @roomidex_relationship, notice: 'Roomidex relationship was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @roomidex_relationship.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /roomidex_relationships/1
  # DELETE /roomidex_relationships/1.json
  def destroy
    @roomidex_relationship.destroy
    respond_to do |format|
      format.html { redirect_to roomidex_relationships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomidex_relationship
      @roomidex_relationship = RoomidexRelationship.find(params[:id])
    end

    def set_roomidex_relationships
      @roomidex_relationships = RoomidexRelationship.where(
        "user_id = ? OR friend_id = ?", 
        current_user.id, 
        current_user.id
      )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomidex_relationship_params
      params.require(:roomidex_relationship).permit(:user_id, :friend_id)
    end
end

app/helpers/roomidex_relationships_helper.rb
module RoomidexRelationshipsHelper
end

app/views/roomidex_relationships/_form.html.erb
<%= simple_form_for(@roomidex_relationship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :friend_id %>
    <%= f.input :index %>
    <%= f.input :show %>
    <%= f.input :create %>
    <%= f.input :destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roomidex_relationships/edit.html.erb
<h1>Editing roomidex_relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @roomidex_relationship %> |
<%= link_to 'Back', roomidex_relationships_path %>

app/views/roomidex_relationships/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Your Roomidex</h1>
      <% @roomidex_relationships.each do |r| %>
        <% user = r.user_id == current_user.id ? r.friend : r.user %>
        <%
          graph = Koala::Facebook::API.new(session[:oauth_token])
          friends_in_common = graph.get_connections(
            "me", 
            "mutualfriends/#{user.uid}"
          ) 
        %>
        <%= 
          render(
            :partial => 'users/user_search_result', 
            :locals => { 
              :user => user,
              :friends_in_common => friends_in_common  
            }
          ) 
        %>
      <% end %>
      <div>
        <%= link_to 'Find more roomates', root_path %>
      </div>
    </div>
  </div>
</section>

app/views/roomidex_relationships/new.html.erb
<h1>New roomidex_relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', roomidex_relationships_path %>

app/views/roomidex_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @roomidex_relationship.user.name %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @roomidex_relationship.friend.name %>
</p>

<%= link_to 'Edit', edit_roomidex_relationship_path(@roomidex_relationship) %> |
<%= link_to 'Back', roomidex_relationships_path %>