config/routes.rb
Roomidex::Application.routes.draw do
  
  resources :messages 

  resources :roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/accept' => 'roomidex_requests#accept', :as => :accept_roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/ignore' => 'roomidex_requests#ignore', :as => :ignore_roomidex_requests

  resources :roomidex_relationships

  root :to => "splash_page#index"

  resources :users

  # Auth resources
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/roomidex_request.rb
class RoomidexRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :receiver, :class_name => "User"

  def self.get_edge(first_id, second_id)
  	request = self.get_directed_edge(first_id, second_id)
  	
  	if request.size == 0 
  		request = self.get_directed_edge(second_id, first_id)
  	end

  	request
  end

  def self.get_directed_edge(first_id, second_id)
  	request = RoomidexRequest.where(
  		user_id: first_id,
  		receiver_id: second_id
	  )
  end
end

app/controllers/roomidex_requests_controller.rb
class RoomidexRequestsController < ApplicationController
  before_action :set_roomidex_request, only: [:show, :edit, :update, :destroy]

  # GET /roomidex_requests
  # GET /roomidex_requests.json
  def index
    @roomidex_requests = RoomidexRequest.all
  end

  # GET /roomidex_requests/1
  # GET /roomidex_requests/1.json
  def show
  end

  # GET /roomidex_requests/new
  def new
    @roomidex_request = RoomidexRequest.new
  end

  # GET /roomidex_requests/1/edit
  def edit
  end

  # POST /roomidex_requests
  # POST /roomidex_requests.json
  def create
    @roomidex_request = current_user.roomidex_requests.build(
      :receiver_id => params[:receiver_id]
    )

    respond_to do |format|
      if @roomidex_request.save
        format.html { 
          redirect_to @roomidex_request, 
          notice: 'Roomidex request was successfully sent.' 
        }
        format.json { 
          render action: 'show', 
          status: :created, 
          location: @roomidex_request 
        }
      else
        format.html { 
          flash[:error] = "Unable to send Roomidex request." 
          redirect_to :back
        }
        format.json { 
          render json: @roomidex_request.errors, 
          status: :unprocessable_entity 
        }
      end
    end
  end

  # PATCH/PUT /roomidex_requests/1
  # PATCH/PUT /roomidex_requests/1.json
  def update
    respond_to do |format|
      if @roomidex_request.update(roomidex_request_params)
        format.html { redirect_to @roomidex_request, notice: 'Roomidex request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @roomidex_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomidex_requests/1
  # DELETE /roomidex_requests/1.json
  def destroy
    @roomidex_request.destroy
    respond_to do |format|
      format.html { redirect_to roomidex_requests_url }
      format.json { head :no_content }
    end
  end

  def accept
    roomidex_request = RoomidexRequest.where(
      "user_id = ? AND receiver_id = ?", 
      params[:user_id], 
      params[:receiver_id]
    ).first

    roomidex_request.accepted = 1
    roomidex_request.ignored = 0

        # Create a roomidex relationship
    roomidex_relationship = RoomidexRelationship.create(
      :user_id => params[:user_id], 
      :friend_id => params[:receiver_id]
    )

    render json: roomidex_request.save
  end

  def ignore
    roomidex_request = RoomidexRequest.where(
      "user_id = ? AND receiver_id = ?", 
      params[:user_id], 
      params[:receiver_id]
    ).first
    
    roomidex_request.accepted = 0
    roomidex_request.ignored = 1

    render json: roomidex_request.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomidex_request
      @roomidex_request = RoomidexRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomidex_request_params
      params.require(:roomidex_request).permit(:user_id, :receiver_id, :accepted, :ignored)
    end
end

app/helpers/roomidex_requests_helper.rb
module RoomidexRequestsHelper
end

app/views/roomidex_requests/_form.html.erb
<%= simple_form_for(@roomidex_request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :requester %>
    <%= f.association :receiver %>
    <%= f.input :accepted %>
    <%= f.input :ignored %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roomidex_requests/_roomidex_requests.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<% @received_roomidex_requests.each do |r| %>
				<div class="alert alert-success roomidexRequest">
					<p>
						<strong><%= r.user.name %></strong> wants to add you to their Roomidex.
					</p>
					<br/>
					<div class="buttons">
						<%= link_to "Accept",
							accept_roomidex_requests_path(r.user.id, current_user.id),
							:method => :post,
							:remote => true,
	 						class: "btn btn-success btn-sm acceptBtn" %>
	 					<%= link_to "Ignore",
							ignore_roomidex_requests_path(r.user.id, current_user.id),
							:method => :post,
							:remote => true,
	 						class: "btn btn-danger btn-sm ignoreBtn" %>
					</div>
					<p class="acceptedResponse hidden">
						<i class="glyphicon glyphicon-ok"></i> Request accepted.
					</p>
					<p class="ignoredResponse hidden text-danger">
						<i class="glyphicon glyphicon-ban-circle"></i> Request ignored.
					</p>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	$('.roomidexRequest .acceptBtn').on('ajax:success', function(){
		$(this).parent('.buttons').hide();
		$(this).parents('.roomidexRequest').find('.acceptedResponse').removeClass('hidden');
	});

	$('.roomidexRequest .ignoreBtn').on('ajax:success', function(){
		$(this).parent('.buttons').hide();
		$(this).parents('.roomidexRequest').find('.ignoredResponse').removeClass('hidden');
	});
</script>

app/views/roomidex_requests/edit.html.erb
<h1>Editing roomidex_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @roomidex_request %> |
<%= link_to 'Back', roomidex_requests_path %>

app/views/roomidex_requests/index.html.erb
<h1>Listing roomidex_requests</h1>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Receiver</th>
      <th>Accepted</th>
      <th>Ignored</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roomidex_requests.each do |roomidex_request| %>
      <tr>
        <td><%= roomidex_request.user.name %></td>
        <td><%= roomidex_request.receiver.name %></td>
        <td><%= roomidex_request.accepted %></td>
        <td><%= roomidex_request.ignored %></td>
        <td><%= link_to 'Show', roomidex_request %></td>
        <td><%= link_to 'Edit', edit_roomidex_request_path(roomidex_request) %></td>
        <td><%= link_to 'Destroy', roomidex_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roomidex request', new_roomidex_request_path %>

app/views/roomidex_requests/new.html.erb
<h1>New roomidex_request</h1>

<%= render 'form' %>

<%= link_to 'Back', roomidex_requests_path %>

app/views/roomidex_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @roomidex_request.user.name %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @roomidex_request.receiver.name %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @roomidex_request.accepted %>
</p>

<p>
  <strong>Ignored:</strong>
  <%= @roomidex_request.ignored %>
</p>

<%= link_to 'Edit', edit_roomidex_request_path(@roomidex_request) %> |
<%= link_to 'Back', roomidex_requests_path %>