config/routes.rb
Roomidex::Application.routes.draw do
  
  resources :messages 

  resources :roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/accept' => 'roomidex_requests#accept', :as => :accept_roomidex_requests
  post '/roomidex_requests/:user_id/:receiver_id/ignore' => 'roomidex_requests#ignore', :as => :ignore_roomidex_requests

  resources :roomidex_relationships

  root :to => "splash_page#index"

  resources :users

  # Auth resources
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-header">
    <%= link_to "Roomidex", root_path, :class => 'navbar-brand' %>
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="
          <%= params[:controller] == "users" && params[:action] == "index" ? 
            "active" : nil %>" >
          <%= link_to raw('<i class="glyphicon glyphicon-search"></i> Search'), users_path %></a>
        </li>

        <li class="
          <%= params[:controller] == "roomidex_relationships" && params[:action] == "index" ? 
            "active" : nil %>" >
          <%= link_to raw('<i class="glyphicon glyphicon-list"></i> My Roomidex'), roomidex_relationships_path %></a>
        </li>

        <li class="
          <%= params[:controller] == "messages" && params[:action] == "index" ? 
            "active" : nil %>" >
          <%= link_to raw('<i class="glyphicon glyphicon-comment"></i>&nbsp; Messages'), messages_path %></a>
        </li>

        <li class="
          <%= params[:controller] == "users" && params[:action] == "show" && params[:id].to_i == current_user.id ? 
            "active" : nil %>" >
          <%= link_to raw('<i class="glyphicon glyphicon-user"></i> ') + current_user.name, user_path(current_user) %></a>
        </li>
        <li>
          <div class="navbar-form">
            <%= link_to 'Logout', signout_path, class: "btn btn-default btn-sm" %>
          </div>
        </li>
      <% else %>
        <li>
          <div class="navbar-form">
            <%= link_to 'Login', signin_path, class: "btn btn-primary" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="navbar-spacer">
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html id=<%= "#{params[:controller]}" + "_" + "#{params[:action]}" %>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roomidex" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Roomidex" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/zqn4ynf.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=572392832842459";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <% if current_user %>
        <%= render 'roomidex_requests/roomidex_requests' %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>